# Generated by Django 5.2.11 on 2026-02-11 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("genre", models.CharField(max_length=50)),
                ("release_year", models.IntegerField(null=True)),
                ("country", models.CharField(max_length=255)),
                ("cover", models.CharField(default="", max_length=300, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_picture",
                    models.ImageField(
                        blank=True,
                        default="profile_images/default.png",
                        upload_to="profile_images",
                    ),
                ),
                ("bio", models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "puzzleID",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("date", models.DateField(unique=True)),
                ("difficulty", models.FloatField(null=True)),
                ("popularity", models.FloatField(null=True)),
                (
                    "isbn",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="bookle.book"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "commentID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("comment", models.CharField(max_length=300)),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "puzzleID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bookle.puzzle"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guesses", models.IntegerField(null=True)),
                ("success", models.BooleanField(default=False)),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True
                    ),
                ),
                (
                    "popularity",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True
                    ),
                ),
                (
                    "puzzleID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bookle.puzzle"
                    ),
                ),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("userID", "puzzleID"), name="unique_score"
                    )
                ],
            },
        ),
    ]
